[tool.ruff]
# Keep lines readable; don’t fight with long LLM prompts in tests.
line-length = 100
target-version = "py311"

# Enable a curated set of rules that catch real issues without being noisy.
extend-select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # import sorting
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "UP",  # pyupgrade
  "SIM", # flake8-simplify
  "N",   # pep8-naming
  "RUF", # ruff-specific
]
# We’ll tolerate long lines in this codebase (FastAPI routes, prompts, SQL).
ignore = ["E501"]

# narrow/expand this as you wish
exclude = [
  ".venv",
  "venv",
  "dist",
  "build",
  "__pycache__",
]

[tool.mypy]
python_version = "3.11"
# Be pragmatic: many libs (faiss, Groq) don’t ship great stubs.
ignore_missing_imports = true
disallow_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
no_implicit_optional = true
pretty = true

# You can gradually enforce strictness per module:
# [[tool.mypy.overrides]]
# module = "app.retrieval.*"
# disallow_untyped_defs = true
